spring:
  application:
      name: FOOD-ORDER-SERVICE
  config:
     import:
        - optional:configserver:http://localhost:9196
  jpa:
      hibernate:
         ddl-auto: update
      show-sql: true
  datasource:
      url: jdbc:mysql://localhost:3306/food_order_service?useSSL=false
      username: root
      password: bismi@mysql123
    #spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
server:
  port: 8080
logging:
  config: C:\intellij projects\Logging Files
