spring:
  application:
     name: FOOD-PAYMENT-SERVICE
  config:
    import:
      - optional:configserver:http://localhost:9196

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/food_payment_service?useSSL=false
    username: root
    password: bismi@mysql123
    #spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

server:
  port: 8081
logging: